version: 2
endpoint: http://terrazuradatalayer.westus2.azurecontainer.io:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://terrazuradatalayer.westus2.azurecontainer.io:8080
