version: '3.6'
services:
  sqlserver:
    container_name: sqlserverdb
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: hasuraMSSQL1
      MSSQL_PID: Express
  postgres:
    container_name: pgdb
    image: postgres:11
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  graphql-engine:
    container_name: core-api
    image: hasura/graphql-engine:v2.0.0-alpha.10
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    - "sqlserver"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/coredb
      HASURA_SQLSERVER_URL: Driver={ODBC Driver 17 for SQL Server};Server=sqlserver;Database=sales_regions;UID=sa;PWD=hasuraMSSQL1;
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  graphql-engine-applications:
    container_name: applications-api
    image: hasura/graphql-engine:v2.0.0-alpha.10
    ports:
      - "8090:8080"
    depends_on:
      - "postgres"
      - "sqlserver"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/applications
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
        ## uncomment next line to set an admin secret
        # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
